name: Lixy CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  jvm-tests:
    name: JVM Tests
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: 426a8cba7a9651be2761a6f78bd46e622c0c4e2dd7d611e21b57154ff97ba5cc
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up Code Climate test reporter
      run: |
        export GIT_COMMIT_SHA=${GITHUB_SHA}
        export GIT_BRANCH=${GITHUB_REF#refs/heads/}
        wget -O cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
        chmod +x cc-test-reporter
        ./cc-test-reporter before-build
    - name: Launch tests
      run: |
        chmod +x gradlew
        ./gradlew jvmTest
        ./gradlew jacocoTestReport
    - name: Upload test coverage to Code Climate
      env:
        JACOCO_SOURCE_PATH: src/commonMain/kotlin src/jvmMain/kotlin
      run: |
        ./cc-test-reporter format-coverage build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml --input-type jacoco
        ./cc-test-reporter upload-coverage
    - name: Run Detekt
      run: |
        ./gradlew detekt
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: build/reportsd/detekt/detekt.sarif
  js-tests:
    name: JS (Node) Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Launch tests
        run: chmod +x gradlew  && ./gradlew jsTest